debug: true
server:
  port: 8080

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-3hpu1z5igskz6tna.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: flea-market-system
