spring.datasource.url=jdbc:postgresql://localhost:5432/fleamarketdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.springframework.security=DEBUG

# SQL scripts for schema and data initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/schema.sql
spring.sql.init.data-locations=classpath:/data.sql

# --- Cloudinary ---
cloudinary.cloud-name=dnkebjtmc
cloudinary.api-key=358896733979818
cloudinary.api-secret=ZyOJIvqfkH3DJa3CgqAWrQr1Ua4

# --- Stripe ---
stripe.api.secretKey=sk_test_51ScMTu3sKEJSVMz59LKqrivVp9VxnRA3jCXt0618nPZRzGI1CvPBRR3VefjUpJZgsJIa7BMUZ9OASOpOG7V2jvy400JxHhNygZ
stripe.public.key=pk_test_51ScMTu3sKEJSVMz5CzZmR3Ud9GCjy12OqZpNjyBG5hJuaKg6voEe5VZyFTyA0C3vYOiQt9wCNrcLs4nvQXWY9dC000Azzy6wxM

# --- LINE Notify ---
line.notify.api.url=https://notify-api.line.me/api/notify
line.notify.token=${LINE_NOTIFY_TOKEN}